In [ ]:
from google.colab import files
uploaded = files.upload()

Saving COSMETICI.xlsx to COSMETICI.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("COSMETICI.xlsx")
categorie= df["categories"]
categorie

0                                                  Arnica
1                 en:Non food products, Open Beauty Facts
2                                                     NaN
3                                                     NaN
4                                                     NaN
                               ...
61423                                                 NaN
61424                                             Shampoo
61425                                                 NaN
61426                                                 NaN
61427    Non food products, Open Beauty Facts, Toothpaste
Name: categories, Length: 61428, dtype: object

In [ ]:
new_categorie = categorie.drop_duplicates().dropna().str.lower()
new_categorie

0                                                   arnica
1                  en:non food products, open beauty facts
6        corps, cheveux, huiles pour le corps, en:hair-...
7                                     en:open-beauty-facts
8        non food products, open beauty facts, cosmetic...
                               ...
61297                                          en:lip balm
61336                                         zuppe pronte
61367                            non alimentaire, en:tests
61386                                                    5
61403                                         საჭმელი ზეთი
Name: categories, Length: 6268, dtype: object

In [ ]:
import re


def remove_lang_prefixes(text):
    if pd.isna(text):
        return text
    # rimuove \"xx:\" all'inizio di una parola, es. \"en:soap\"
    return re.sub(r"\b[a-z]{2}:", "", str(text))

new_categorie= new_categorie.apply(remove_lang_prefixes)
new_categorie

0                                                   arnica
1                     non food products, open beauty facts
6        corps, cheveux, huiles pour le corps, hair-oil...
7                                        open-beauty-facts
8        non food products, open beauty facts, cosmetic...
                               ...
61297                                             lip balm
61336                                         zuppe pronte
61367                               non alimentaire, tests
61386                                                    5
61403                                         საჭმელი ზეთი
Name: categories, Length: 6268, dtype: object

In [ ]:
new_categorie.to_excel("categorie_estratte.xlsx", index=False)
from google.colab import files
files.download("categorie_estratte.xlsx")